[package]
name = "dnagenerator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23"
rand = "0.8"
rand_chacha = "0.3.1"
rayon = "1.5.1"